### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by abougouffa** [gliwka/atom-zeal#2]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/local/share/atom/resources/app/src/atom.js:54:11)
Object.activate (/home/abougouffa/.atom/packages/atom-zeal/lib/atom-zeal.coffee:6:9)
```

**Comment by bb010g** [comment]
bumpity bump

**Comment by stefancocora** [comment]
+1 came across this one today

**Comment by gliwka** [comment]
Thanks, it's now fixed!

**Comment by stefancocora** [comment]
Good work , the deprecation cop is happy now :+1:
