### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by MortalCatalyst** [gliwka/atom-zeal#3]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/atom/resources/app/src/atom.js:54:11)
Object.activate (/home/sayth/.atom/packages/atom-zeal/lib/atom-zeal.coffee:6:9)
```

**Comment by gliwka** [comment]
Duplicate, see issue #2
