### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [gliwka/atom-zeal#6]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.1.0`) of this package:

1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
1. The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see what deprecations are being reported on this package.

See https://github.com/atom/atom/issues/6867 for more info.

**Comment by gliwka** [comment]
Thanks, it's now fixed!
